spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: liangbing39024&
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #        namespace: b9378992-51d7-45c1-aa33-ad0bb12bf387
#        cluster-name: NJ
  application:
    name: user-center
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
  servlet:
    context-path: /user-center
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 192.168.18.8:9876
