spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: liangbing39024&
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: b9378992-51d7-45c1-aa33-ad0bb12bf387
server:
  port: 8081
  servlet:
    context-path: /content-center