spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: liangbing39024&
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
server:
  port: 8081
  servlet:
    context-path: /content-center
#user-center:
#  ribbon:
ribbon:
  eager-load:
    enabled: true
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#feign的性能优化，第一就是日志级别，设置为basic，第二就是使用httpclient或okhttp来设置连接池，以及单路径最大连接数。
feign:
  client:
    config:
      #想要调用的微服务的名称
      user-center:
        loggerLevel: full
  #feign:
  #  client:
  #    config:
  #      #全局配置
  #      default:
  #        loggerLevel: full
  httpclient:
    #让feign使用apache的httpclient做请求，而不是默认的urlconnection
    enabled: true
    #feign的最大连接数
    max-connections: 200
    #feign单个路径的最大连接数
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  name-server: 192.168.18.8:9876
  producer:
    group: test-group
  # 小坑：必须指定group
logging:
  level:
    com.alibab.nacos: error
